project_id                              = "solvook-infra"   # replace with your project id
region                                  = "asia-northeast3" # replace with your region
dify_version                            = "latest"
dify_plugin_daemon_version              = "latest-local"
dify_sandbox_version                    = "latest"
nginx_repository_id                     = "dify-nginx-repo"
web_repository_id                       = "dify-web-repo"
api_repository_id                       = "dify-api-repo"
plugin_daemon_repository_id             = "dify-plugin-daemon-repo"
sandbox_repository_id                   = "dify-sandbox-repo"
db_username                             = "postgres"
db_port                                 = "5432"
db_database                             = "dify"
db_database_plugin                      = "dify_plugin"
db_deletion_protection                  = true
storage_type                            = "google-storage"
google_storage_bucket_name              = "dify"
vector_store                            = "pgvector"
indexing_max_segmentation_tokens_length = "1000"
cloud_run_ingress                       = "INGRESS_TRAFFIC_ALL" # recommend to setup load balancer and use "INGRESS_TRAFFIC_INTERNAL_LOAD_BALANCER"
min_instance_count                      = 1
max_instance_count                      = 5
slack_channel_name                      = "#creator-backend-alert"
spreadsheet_id                          = "1R8uj87uCbJA5YxZSFWlEvJKjgIWZQCNh-EldR33fYLY"
sheet_name                              = "data"
unique_id_column                        = "id"
dify_api_endpoint                       = "https://dify-service-1030217702417.asia-northeast3.run.app/v1/workflows/run"
dify_api_key_secret_id                  = "dify-api-key"
dify_api_timeout_minutes                = 10
google_sheets_credentials_secret_id     = "dify-batch-processor-credentials"
passage_analysis_workflow_id            = "0a179409-d6ee-46e2-bf78-83fd7d415123"
passage_workbook_workflow_id            = "9aa5df68-9912-4a74-8379-04eee2db8994"